import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateVideoCandidate,validateVideoReport,validateYouTubeStatus,saveOptionalVideoReport,attachOptionalVideo,maintainOptionalVideos} from '../supabase/functions/_shared/optional-learning-videos.mjs';

const id = 'a1000000-0000-4000-8000-000000000001';
const candidate={learner_id:id,quiz_version_id:id,program_id:id,curriculum_id:id,grade_level:7,subject_id:1,concept_id:id,position:1,video_ref:'qaVideo0001',title:'Vetted explanation',language:'tr',rationale:'Matches the exact target concept.'};
assert.deepEqual(validateVideoCandidate(candidate),candidate);
for(const change of [{grade_level:0},{grade_level:13},{subject_id:NaN},{position:0},{position:21},{position:1.5},{video_ref:'https://youtube.com/test'},{language:'xx'},{title:''},{concept_id:'bad'},{watched_seconds:3}]) assert.throws(()=>validateVideoCandidate({...candidate,...change}),/INVALID_VIDEO_INPUT/);
const report={action:'save_video_report',attempt_id:id,video_id:id,self_report:'watched_part',expected_revision:0,request_id:id};
assert.equal(validateVideoReport(report).self_report,'watched_part');
for(const value of ['not_reported','not_watched','watched_part','watched_full']) assert.equal(validateVideoReport({...report,self_report:value}).self_report,value);
for(const change of [{self_report:'completed'},{expected_revision:-1},{expected_revision:1.5},{request_id:'bad'},{learner_id:id},{watch_percentage:80},{played_seconds:50}]) assert.throws(()=>validateVideoReport({...report,...change}),/INVALID_VIDEO_INPUT/);

const now=Date.parse('2026-10-02T15:00:00Z');
function response(status={embeddable:true,madeForKids:true,privacyStatus:'public'},videoRef=candidate.video_ref){return {ok:true,json:async()=>({items:[{id:videoRef,status}]})};}
let requested;
const verified=await validateYouTubeStatus(candidate.video_ref,{apiKey:'synthetic-test-key',now,fetchImpl:async(url,options)=>{requested={url,options};return response();}});
assert.equal(verified.embeddable,true);
assert.equal(verified.made_for_kids,true);
assert.equal(Date.parse(verified.verification_expires_at)-now,7*86400000);
assert.equal(new URL(requested.url).searchParams.get('part'),'id,status');
assert.equal(new URL(requested.url).searchParams.get('id'),candidate.video_ref);
assert.ok(!requested.url.includes('synthetic-test-key'));
assert.equal(requested.options.headers['X-Goog-Api-Key'],'synthetic-test-key');
assert.ok(!new URL(requested.url).searchParams.get('fields').includes('statistics'));
assert.equal((await validateYouTubeStatus(candidate.video_ref,{apiKey:'synthetic-test-key',now,fetchImpl:async()=>response({embeddable:true,madeForKids:false,privacyStatus:'unlisted'})})).made_for_kids,false);
for(const status of [{embeddable:false,madeForKids:true,privacyStatus:'public'},{embeddable:true,privacyStatus:'public'},{embeddable:true,madeForKids:'false',privacyStatus:'public'},{embeddable:true,madeForKids:false,privacyStatus:'private'}]) await assert.rejects(validateYouTubeStatus(candidate.video_ref,{apiKey:'synthetic-test-key',fetchImpl:async()=>response(status)}),/VIDEO_PROVIDER_UNAVAILABLE/);
for(const fetchImpl of [async()=>({ok:false}),async()=>({ok:true,json:async()=>({items:[]})}),async()=>response(undefined,'differentID'),async()=>{throw new Error('Synthetic provider detail');}]) await assert.rejects(validateYouTubeStatus(candidate.video_ref,{apiKey:'synthetic-test-key',fetchImpl}),/^Error: VIDEO_PROVIDER_UNAVAILABLE$/);
await assert.rejects(validateYouTubeStatus(candidate.video_ref,{}),/VIDEO_PROVIDER_UNAVAILABLE/);
let calls=[];
const trace={measure:async(_label,_options,fn)=>fn()};
const admin={rpc:async(name,params)=>{calls.push({name,params});return {data:{ok:true,self_report:'watched_part',report_revision:1}};}};
await saveOptionalVideoReport(admin,'verified-workspace','verified-learner',report,trace);
assert.equal(calls[0].params.p_learner_id,'verified-learner');
assert.equal(calls[0].params.p_workspace_id,'verified-workspace');
assert.equal(calls.length,1);
await assert.rejects(saveOptionalVideoReport({rpc:async()=>({data:{error:'REPORT_CONFLICT',self_report:'watched_full',report_revision:2}})},'w','l',report,trace),e=>e.message==='REPORT_CONFLICT'&&e.data.report_revision===2);
calls=[];
await attachOptionalVideo(admin,'verified-workspace','verified-parent',{video:candidate},trace,{apiKey:'synthetic-test-key',now,fetchImpl:async()=>response()});
assert.equal(calls[0].params.p_parent_id,'verified-parent');
assert.equal(calls[0].params.p_candidate.made_for_kids,true);
assert.equal(calls[0].params.p_candidate.position,1,'attachment carries explicit ordered position');
calls=[];
await assert.rejects(attachOptionalVideo(admin,'w','p',{video:candidate},trace,{apiKey:'synthetic-test-key',fetchImpl:async()=>response({embeddable:false,madeForKids:true,privacyStatus:'public'})}),/VIDEO_PROVIDER_UNAVAILABLE/);
assert.equal(calls.length,0,'Provider rejection must stop before attachment persistence');
const statusRevision='a1000000-0000-4000-8000-000000000002';
const lookup={select(fields){assert.equal(fields,'id,video_revision,status_revision,video_ref');return this;},eq(){return this;},maybeSingle:async()=>({data:{id,video_revision:id,status_revision:statusRevision,video_ref:candidate.video_ref}})};
await maintainOptionalVideos({...admin,from:()=>lookup},'w',{action:'refresh_optional_video',assignment_id:id},trace,{});
assert.equal(calls.at(-1).params.p_status,null,'Refresh failure must clear stale status through the atomic RPC');
assert.equal(calls.at(-1).params.p_status_revision,statusRevision,'Refresh must carry the separately captured validation token');
assert.equal(calls.at(-1).params.p_video_revision,id,'Validation token must not change pinned video identity');
let conflictCalls=0;
await assert.rejects(maintainOptionalVideos({from:()=>lookup,rpc:async(_name,params)=>{conflictCalls++;assert.equal(params.p_status_revision,statusRevision);assert.equal(params.p_status.made_for_kids,true);return {data:{error:'VIDEO_STATUS_CONFLICT'}};}},'w',{action:'refresh_optional_video',assignment_id:id},trace,{apiKey:'synthetic-test-key',now,fetchImpl:async()=>response()}),/^Error: VIDEO_STATUS_CONFLICT$/);
assert.equal(conflictCalls,1,'An outdated provider response must not retry with a newer validation token');
// Execute the actual API response boundary, removing only its TypeScript assertion.
const learningApi=fs.readFileSync('supabase/functions/learning-api/index.ts','utf8');
const apiCatch=learningApi.match(/\}catch\(e\)\{([\s\S]*?)\r?\n  \}\r?\n\}\);\s*$/);
assert.ok(apiCatch,'Learning API error response block must be available to the regression');
const errorResponse=new Function('e','trace','origin','cors','performanceJsonResponse',apiCatch[1].replace('(e as any)','e'));
const respondToError=error=>errorResponse(error,trace,'https://testing.example',origin=>({origin}),(_trace,payload,status)=>({payload,status}));
const providerError=new Error('VIDEO_PROVIDER_UNAVAILABLE');
providerError.data={raw_provider_payload:'Synthetic sensitive provider detail'};
assert.deepEqual(respondToError(providerError),{payload:{error:'VIDEO_PROVIDER_UNAVAILABLE'},status:422},'Expected provider rejection is an opaque 422, not a server failure');
for(const [message,status] of [['AUTH_REQUIRED',401],['INVALID_PARENT_SESSION',401],['VIDEO_ATTACHMENT_FORBIDDEN',403],['QUIZ_NOT_AVAILABLE',404],['VIDEO_NOT_AVAILABLE',404],['VIDEO_REPORT_REQUEST_CONFLICT',409],['VIDEO_STATUS_CONFLICT',409],['INVALID_VIDEO_INPUT',400],['VIDEO_CONTEXT_MISMATCH',400],['ATTEMPT_NOT_ACTIVE',400],['VIDEO_ATTACHMENT_UNAVAILABLE',500],['SERVER_ERROR',500]]) assert.deepEqual(respondToError(new Error(message)),{payload:{error:message},status},`${message} keeps its existing API status`);
const reportConflict=new Error('REPORT_CONFLICT');
reportConflict.data={self_report:'watched_full',report_revision:2,raw_provider_payload:'Synthetic sensitive provider detail'};
assert.deepEqual(respondToError(reportConflict),{payload:{error:'REPORT_CONFLICT',self_report:'watched_full',report_revision:2},status:409},'Report conflicts expose only the authoritative self-report/revision');
assert.deepEqual(respondToError({message:'Synthetic unknown thrown value'}),{payload:{error:'SERVER_ERROR'},status:500});
const migration=fs.readFileSync('supabase/migrations/20261002193353_optional_learning_videos.sql','utf8');
const sequenceMigration=fs.readFileSync('supabase/migrations/20261004170500_optional_learning_video_sequence.sql','utf8');
assert.match(migration,/\"enabled\":false/);
assert.match(migration,/v_optional_video := private\.flh_learning_optional_video/);
assert.match(migration,/raise warning 'flh_learning_start optional video skipped \(SQLSTATE %\)', sqlstate;/,'Optional failure diagnostics must log only the stable SQLSTATE');
assert.match(sequenceMigration,/unique \(workspace_id, learner_id, quiz_version_id, position\)/i,'sequence positions are unique per learner/version');
assert.match(sequenceMigration,/jsonb_build_object\('videos',items\)/,'multi-video response is nested under the backward-compatible optional_video payload');
assert.match(sequenceMigration,/where workspace_id=p_workspace_id and attempt_id=p_attempt_id and video_id=p_video_id/,'self-report updates only the selected video snapshot');
const featureSources=[migration,sequenceMigration,fs.readFileSync('supabase/functions/_shared/optional-learning-videos.mjs','utf8')].join('\n');
assert.doesNotMatch(featureSources,/getCurrentTime|getDuration|onStateChange|played_seconds|watch_percentage|watch_seconds/);
assert.doesNotMatch(migration,/insert into public\.(gamification_events|learner_gamification_state)/i);
console.log('Optional video candidate/provider-status/self-report tests passed; no player evidence or reward coupling.');
