import { chromium } from 'playwright';
import fs from 'node:fs';

const BASE_URL=process.env.APP_URL||'http://127.0.0.1:4173/';
const SAVE_DELAY_MS=Number(process.env.PERF_SAVE_DELAY_MS||2500);
const LIMITS={appReadyMs:Number(process.env.PERF_APP_READY_LIMIT_MS||2500),learningOpenUiMs:800,examOpenUiMs:Number(process.env.PERF_EXAM_OPEN_LIMIT_MS||800),answerVisualMs:Number(process.env.PERF_ANSWER_VISUAL_LIMIT_MS||250),nextQuestionMs:Number(process.env.PERF_NEXT_QUESTION_LIMIT_MS||250),resultUiMs:Number(process.env.PERF_RESULT_UI_LIMIT_MS||800)};
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const errors=[];let learningDraftStarted=0,learningDraftCompleted=0,examSaveStarted=0,examSaveCompleted=0;
page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});

await page.route('**/functions/v1/**',async route=>{const req=route.request();let b={};try{b=JSON.parse(req.postData()||'{}')}catch{};const slug=new URL(req.url()).pathname.split('/').pop();
  if(slug==='learning-api'&&b.action==='start_quiz')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({attempt_id:'lp',resumed:false,quiz:{slug:'perf',title:'تعلم الأداء'},queue:[{question_id:'lq',source_role:'core',status:'active',draft_option_position:null,hint_level_requested:0,question:{id:'lq',prompt:'اختر',options:[{position:1,content:'أول'},{position:2,content:'ثان'}],assets:[]}}]})});
  if(slug==='learning-api'&&b.action==='save_draft'){learningDraftStarted=Date.now();await new Promise(r=>setTimeout(r,SAVE_DELAY_MS));learningDraftCompleted=Date.now();try{return await route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'})}catch{return;}}
  if(slug==='learning-api'&&b.action==='answer')return route.fulfill({status:200,contentType:'application/json',body:'{"is_correct":true,"finalized":true,"explanation":"صحيح"}'});
  if(slug==='learning-api'&&b.action==='finish_quiz')return route.fulfill({status:200,contentType:'application/json',body:'{"percentage":100,"first_try_correct":1,"hints_used":0,"award":{"already_awarded":true},"review":[]}'});
  if(slug==='exam-v2-api'&&b.action==='warmup')return route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'});
  if(slug==='exam-v2-api'&&b.action==='start_exam')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({attempt_id:'ep',resumed:false,quiz:{slug:'perf',title:'امتحان الأداء'},questions:[{question_id:'e1',saved_response:null,is_flagged:false,question:{id:'e1',prompt:'2 + 2 = ؟',options:[{position:1,content:'3'},{position:2,content:'4'}],assets:[]}},{question_id:'e2',saved_response:null,is_flagged:false,question:{id:'e2',prompt:'3 + 1 = ؟',options:[{position:1,content:'4'},{position:2,content:'6'}],assets:[]}}]})});
  if(slug==='exam-v2-api'&&b.action==='save_answer'){examSaveStarted=Date.now();await new Promise(r=>setTimeout(r,SAVE_DELAY_MS));examSaveCompleted=Date.now();try{return await route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'})}catch{return;}}
  if(slug==='exam-v2-api'&&b.action==='submit_exam')return route.fulfill({status:200,contentType:'application/json',body:'{"percentage":100,"score_points":2,"max_points":2,"review":[]}'});
  if(slug==='exam-v2-api'&&b.action==='set_flag')return route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'});
  if(slug==='family-api'&&b.action==='student_profile')return route.fulfill({status:200,contentType:'application/json',body:'{"learner":{"id":"p","display_name":"أداء","slug":"perf","grade_level":5,"is_test":true},"gamification":{"xp":0,"reward_points":0,"current_level":1,"current_streak":0,"longest_streak":0,"badges":[],"rewards":[]}}'});
  if(slug==='family-api'&&b.action==='learner_choices')return route.fulfill({status:200,contentType:'application/json',body:'{"learners":[]}'});
  if(slug==='student-library-api')return route.fulfill({status:200,contentType:'application/json',body:'{"programs":[],"standalone_books":[]}'});
  return route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'});
});
await page.addInitScript(()=>localStorage.setItem('learner_session','perf-session'));
const navStart=Date.now();await page.goto(`${BASE_URL}?performance=${Date.now()}`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>Boolean(window.FLH?.startExamQuiz&&window.FLH?.startLearningQuiz),null,{timeout:10000});const appReadyMs=Date.now()-navStart;

const learningStart=Date.now();await page.evaluate(()=>window.FLH.startLearningQuiz('perf'));await page.locator('.flh-learn-answer').first().waitFor({state:'visible',timeout:5000});const learningOpenUiMs=Date.now()-learningStart;
const learningAnswerVisualMs=await page.evaluate(async()=>{const b=document.querySelector('.flh-learn-answer');const s=performance.now();b.click();return await new Promise((resolve,reject)=>{const tick=()=>{if(document.querySelector('.flh-learn-answer.selected'))return resolve(performance.now()-s);if(performance.now()-s>1200)return reject(new Error('LEARNING_VISUAL_TIMEOUT'));requestAnimationFrame(tick)};tick()})});
for(let i=0;i<40&&!learningDraftStarted;i++)await page.waitForTimeout(25);const learningDraftPending=Boolean(learningDraftStarted&&!learningDraftCompleted);
await page.locator('.flh-learn-answer').nth(1).click();await page.locator('.flh-learn-answer.selected[data-pos="2"]').waitFor({state:'visible',timeout:500});if(await page.locator('#flhConfirmAnswer').isDisabled())throw new Error('LEARNING_CONFIRM_DISABLED');await page.locator('#flhConfirmAnswer').click();await page.locator('#flhLearnNext').waitFor({state:'visible',timeout:1500});

const examStart=Date.now();await page.evaluate(()=>window.FLH.startExamQuiz('perf'));await page.locator('.exam-v3-answer').first().waitFor({state:'visible',timeout:5000});const examOpenUiMs=Date.now()-examStart;
const examAnswerVisualMs=await page.evaluate(async()=>{const b=document.querySelector('.exam-v3-answer');const s=performance.now();b.click();return await new Promise((resolve,reject)=>{const tick=()=>{if(document.querySelector('.exam-v3-answer.selected'))return resolve(performance.now()-s);if(performance.now()-s>1200)return reject(new Error('EXAM_VISUAL_TIMEOUT'));requestAnimationFrame(tick)};tick()})});
for(let i=0;i<40&&!examSaveStarted;i++)await page.waitForTimeout(25);const nextQuestionMs=await page.evaluate(async()=>{const b=document.querySelector('#examNext');const s=performance.now();b.click();return await new Promise((resolve,reject)=>{const tick=()=>{if(document.body.textContent.includes('السؤال 2 من 2'))return resolve(performance.now()-s);if(performance.now()-s>1200)return reject(new Error('NEXT_TIMEOUT'));requestAnimationFrame(tick)};tick()})});const examSavePendingDuringNavigation=Boolean(examSaveStarted&&!examSaveCompleted);
await page.locator('.exam-v3-answer').first().click();await page.waitForTimeout(SAVE_DELAY_MS+150);const resultStart=Date.now();await page.locator('#examSubmit').click();await page.getByText('نتيجة الامتحان',{exact:false}).waitFor({state:'visible',timeout:5000});const resultUiMs=Date.now()-resultStart;

const report={generated_at:new Date().toISOString(),base_url:BASE_URL,injected_save_delay_ms:SAVE_DELAY_MS,measurements:{app_ready_ms:appReadyMs,learning_open_ui_ms:learningOpenUiMs,learning_answer_visual_ms:+learningAnswerVisualMs.toFixed(1),exam_open_ui_ms:examOpenUiMs,exam_answer_visual_ms:+examAnswerVisualMs.toFixed(1),next_question_ms:+nextQuestionMs.toFixed(1),result_ui_ms:resultUiMs},learning_draft_pending_during_reselection:learningDraftPending,exam_save_pending_during_navigation:examSavePendingDuringNavigation,browser_errors:errors};
fs.writeFileSync('performance-report.json',JSON.stringify(report,null,2));
const failures=[];if(appReadyMs>LIMITS.appReadyMs)failures.push(`app ready ${appReadyMs}ms`);if(learningOpenUiMs>LIMITS.learningOpenUiMs)failures.push(`learning open ${learningOpenUiMs}ms`);if(learningAnswerVisualMs>LIMITS.answerVisualMs)failures.push(`learning visual ${learningAnswerVisualMs.toFixed(1)}ms`);if(examOpenUiMs>LIMITS.examOpenUiMs)failures.push(`exam open ${examOpenUiMs}ms`);if(examAnswerVisualMs>LIMITS.answerVisualMs)failures.push(`exam visual ${examAnswerVisualMs.toFixed(1)}ms`);if(nextQuestionMs>LIMITS.nextQuestionMs)failures.push(`next ${nextQuestionMs.toFixed(1)}ms`);if(resultUiMs>LIMITS.resultUiMs)failures.push(`result ${resultUiMs}ms`);if(!learningDraftPending)failures.push('Learning draft delay did not overlap reselection');if(!examSavePendingDuringNavigation)failures.push('Exam save delay did not overlap navigation');if(errors.length)failures.push(...errors);
const md=['## Family Learning Hub performance smoke','',`Learning selection: **${learningAnswerVisualMs.toFixed(1)} ms**`,`Exam selection: **${examAnswerVisualMs.toFixed(1)} ms**`,`Learning open: **${learningOpenUiMs} ms**`,`Exam open: **${examOpenUiMs} ms**`,`Injected save delay: **${SAVE_DELAY_MS} ms**`,`Learning reselection while draft pending: **${learningDraftPending?'PASS':'FAIL'}**`,`Exam navigation while save pending: **${examSavePendingDuringNavigation?'PASS':'FAIL'}**`,failures.length?`\n❌ ${failures.join('; ')}`:'\n✅ Performance smoke passed.'].join('\n');fs.writeFileSync('performance-summary.md',md);console.log(md);await browser.close();if(failures.length)throw new Error(`Performance regression: ${failures.join('; ')}`);