import { createClient } from "npm:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const WORKSPACE_ID="55f9224c-8ba7-4cbc-9f88-713e6a6b41df";
function cors(o:string|null){const a=new Set(["https://fadiaboalward.github.io","http://localhost:5173","http://localhost:4173"]);return{"Access-Control-Allow-Origin":o&&a.has(o)?o:"https://fadiaboalward.github.io","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function json(d:unknown,s=200,o:string|null=null){return new Response(JSON.stringify(d),{status:s,headers:cors(o)})}
function fb(s:string){const n=s.replaceAll("-","+").replaceAll("_","/")+"===".slice((s.length+3)%4),r=atob(n);return new Uint8Array([...r].map(c=>c.charCodeAt(0)))}
function tb(b:Uint8Array){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
async function hm(d:string){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(SERVICE_ROLE),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return tb(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(d))))}
async function learner(req:Request){const a=req.headers.get("authorization")||"";if(!a.startsWith("Bearer "))throw new Error("AUTH_REQUIRED");const[b,s]=a.slice(7).trim().split(".");if(!b||!s||await hm(b)!==s)throw new Error("INVALID_SESSION");const p=JSON.parse(new TextDecoder().decode(fb(b)));if(p.typ!=="learner"||p.workspace_id!==WORKSPACE_ID||!p.learner_id)throw new Error("INVALID_SESSION");if(!p.exp||p.exp<Math.floor(Date.now()/1000))throw new Error("SESSION_EXPIRED");return String(p.learner_id)}
async function codes(lid:string,b:any){const aid=String(b.attempt_id||"");if(!aid)throw new Error("ATTEMPT_REQUIRED");const{data:a}=await admin.from("quiz_attempts").select("id").eq("workspace_id",WORKSPACE_ID).eq("id",aid).eq("learner_id",lid).maybeSingle();if(!a)throw new Error("ATTEMPT_NOT_FOUND");const{data:qrows}=await admin.from("quiz_attempt_question_queue").select("question_id").eq("workspace_id",WORKSPACE_ID).eq("quiz_attempt_id",aid);const ids=[...new Set((qrows||[]).map((x:any)=>x.question_id))];if(!ids.length)return{codes:{}};const{data:qs}=await admin.from("quiz_questions").select("id,question_code").eq("workspace_id",WORKSPACE_ID).in("id",ids);return{codes:Object.fromEntries((qs||[]).map((q:any)=>[q.id,q.question_code]))}}
Deno.serve(async(req:Request)=>{const o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o)});if(req.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405,o);try{const lid=await learner(req),b=await req.json().catch(()=>({})),a=String(b.action||"");if(a==="codes")return json(await codes(lid,b),200,o);return json({error:"UNKNOWN_ACTION"},400,o)}catch(e){const m=e instanceof Error?e.message:"SERVER_ERROR";return json({error:m},["AUTH_REQUIRED","INVALID_SESSION","SESSION_EXPIRED"].includes(m)?401:m==="ATTEMPT_NOT_FOUND"?404:m==="ATTEMPT_REQUIRED"?400:500,o)}});