import { createClient } from "npm:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});const WORKSPACE_ID="55f9224c-8ba7-4cbc-9f88-713e6a6b41df";
function cors(origin:string|null){const allowed=new Set(["https://fadiaboalward.github.io","http://localhost:5173","http://localhost:4173"]);return{"Access-Control-Allow-Origin":origin&&allowed.has(origin)?origin:"https://fadiaboalward.github.io","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function json(data:unknown,status=200,origin:string|null=null){return new Response(JSON.stringify(data),{status,headers:cors(origin)})}
function fromB64url(s:string){const norm=s.replaceAll("-","+").replaceAll("_","/")+"===".slice((s.length+3)%4),raw=atob(norm);return new Uint8Array([...raw].map(c=>c.charCodeAt(0)))}function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}async function hmac(data:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(SERVICE_ROLE),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64url(new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(data))))}
async function learner(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("AUTH_REQUIRED");const[body,sig]=auth.slice(7).trim().split(".");if(!body||!sig||await hmac(body)!==sig)throw new Error("INVALID_SESSION");const p=JSON.parse(new TextDecoder().decode(fromB64url(body)));if(p.typ!=="learner"||p.workspace_id!==WORKSPACE_ID||!p.learner_id)throw new Error("INVALID_SESSION");if(!p.exp||p.exp<Math.floor(Date.now()/1000))throw new Error("SESSION_EXPIRED");return String(p.learner_id)}
function cleanQuiz(q:any){return{id:q.id,slug:q.slug,title:q.title,description:q.description,quiz_kind:q.quiz_kind,unit_id:q.unit_id,book_id:q.book_id,delivery_config:q.delivery_config||{}}}
function buildBook(book:any,units:any[],quizzes:any[]){const unitRows=units.filter(u=>u.book_id===book.id).sort((a,b)=>a.sort_order-b.sort_order).map(u=>({id:u.id,slug:u.slug,title:u.title,sort_order:u.sort_order,metadata:u.metadata||{},quizzes:quizzes.filter(q=>q.unit_id===u.id).map(cleanQuiz)}));const unitIds=new Set(unitRows.map(u=>u.id));const extras=quizzes.filter(q=>q.book_id===book.id&&(!q.unit_id||!unitIds.has(q.unit_id))).map(cleanQuiz);return{id:book.id,code:book.code,title:book.title,grade_level:book.grade_level,school_year:book.school_year,language:book.language,source_kind:book.source_kind,subject:book.subject||null,units:unitRows,extras}}
async function catalog(learnerId:string){const[{data:enrs},{data:direct}]=await Promise.all([admin.from("learner_program_enrollments").select("id,is_primary,started_at,program:learning_programs(id,slug,code,title,description,program_type,grade_level,school_year,primary_language,status)").eq("workspace_id",WORKSPACE_ID).eq("learner_id",learnerId).eq("status","active"),admin.from("learner_content_assignments").select("id,resource_type,resource_id,status").eq("workspace_id",WORKSPACE_ID).eq("learner_id",learnerId).eq("status","active")]);const programs=(enrs||[]).filter((e:any)=>e.program?.status==="active"),programIds=programs.map((e:any)=>e.program.id);let pbooks:any[]=[],pqs:any[]=[];if(programIds.length){const[r1,r2]=await Promise.all([admin.from("program_books").select("program_id,book_id,is_required,sort_order").eq("workspace_id",WORKSPACE_ID).in("program_id",programIds).order("sort_order"),admin.from("program_quizzes").select("program_id,quiz_id,sort_order,availability").eq("workspace_id",WORKSPACE_ID).in("program_id",programIds).eq("availability","available").order("sort_order")]);pbooks=r1.data||[];pqs=r2.data||[]}
const directBookIds=(direct||[]).filter((x:any)=>x.resource_type==="book").map((x:any)=>x.resource_id),directUnitIds=(direct||[]).filter((x:any)=>x.resource_type==="unit").map((x:any)=>x.resource_id),directQuizIds=(direct||[]).filter((x:any)=>x.resource_type==="quiz").map((x:any)=>x.resource_id);let directUnits:any[]=[],directQuizzes:any[]=[];if(directUnitIds.length){const{data}=await admin.from("units").select("id,book_id").in("id",directUnitIds);directUnits=data||[]}if(directQuizIds.length){const{data}=await admin.from("quizzes").select("id,book_id,unit_id").eq("workspace_id",WORKSPACE_ID).in("id",directQuizIds);directQuizzes=data||[]}
const allBookIds=[...new Set([...pbooks.map((x:any)=>x.book_id),...directBookIds,...directUnits.map((x:any)=>x.book_id),...directQuizzes.map((x:any)=>x.book_id).filter(Boolean)])];if(!allBookIds.length)return{programs:programs.map((e:any)=>({enrollment_id:e.id,is_primary:e.is_primary,...e.program,books:[]})),standalone_books:[]};
const[{data:books},{data:units},{data:quizzes0}]=await Promise.all([admin.from("books").select("id,code,title,grade_level,school_year,language,source_kind,curriculum_id,subject:subjects(id,code,name_ar,name_en)").in("id",allBookIds),admin.from("units").select("id,book_id,slug,title,sort_order,metadata").in("book_id",allBookIds).order("sort_order"),admin.from("quizzes").select("id,slug,title,description,quiz_kind,delivery_config,book_id,unit_id,status").eq("workspace_id",WORKSPACE_ID).eq("status","active").in("book_id",allBookIds)]);const quizzes=quizzes0||[],quizIds=quizzes.map((q:any)=>q.id);let published=new Set<string>();if(quizIds.length){const{data:versions}=await admin.from("quiz_versions").select("quiz_id").eq("workspace_id",WORKSPACE_ID).eq("state","published").in("quiz_id",quizIds);published=new Set((versions||[]).map((v:any)=>v.quiz_id))}const activeQs=quizzes.filter((q:any)=>published.has(q.id)),bookMap=new Map((books||[]).map((b:any)=>[b.id,b])),unitRows=units||[];
const programResult=programs.map((e:any)=>{const rows=pbooks.filter((x:any)=>x.program_id===e.program.id).sort((a:any,b:any)=>a.sort_order-b.sort_order),allowed=new Set(pqs.filter((x:any)=>x.program_id===e.program.id).map((x:any)=>x.quiz_id));return{enrollment_id:e.id,is_primary:e.is_primary,started_at:e.started_at,...e.program,books:rows.map((pb:any)=>{const b=bookMap.get(pb.book_id);if(!b)return null;return{...buildBook(b,unitRows,activeQs.filter((q:any)=>allowed.has(q.id))),is_required:pb.is_required,sort_order:pb.sort_order}}).filter(Boolean)}});
const programBookIds=new Set(pbooks.map((x:any)=>x.book_id)),directBookSet=new Set(directBookIds),directUnitSet=new Set(directUnitIds),directQuizSet=new Set(directQuizIds),standaloneIds=allBookIds.filter(id=>!programBookIds.has(id));const standalone=standaloneIds.map(id=>{const b=bookMap.get(id);if(!b)return null;const allowed=activeQs.filter((q:any)=>q.book_id===id&&(directBookSet.has(id)||(q.unit_id&&directUnitSet.has(q.unit_id))||directQuizSet.has(q.id)));return{...buildBook(b,unitRows,allowed),access_origin:directBookSet.has(id)?"book":"direct"}}).filter(Boolean);return{programs:programResult,standalone_books:standalone}}
Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(req.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405,origin);try{const learnerId=await learner(req),body=await req.json().catch(()=>({})),action=String(body.action||"catalog");if(action!=="catalog")return json({error:"UNKNOWN_ACTION"},400,origin);return json(await catalog(learnerId),200,origin)}catch(e){const msg=e instanceof Error?e.message:"SERVER_ERROR";return json({error:msg},["AUTH_REQUIRED","INVALID_SESSION","SESSION_EXPIRED"].includes(msg)?401:500,origin)}});
