import { createClient } from "npm:@supabase/supabase-js@2";
import { createBackendPerformanceTrace, performanceJsonResponse } from "../_shared/backend-performance.mjs";
import { completeJourneyRows, deriveLearnerJourney, eligibleJourneyAssignments, JOURNEY_ROW_LIMIT, readJourneyProgress } from "../_shared/learner-journey.mjs";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const WORKSPACE_ID="55f9224c-8ba7-4cbc-9f88-713e6a6b41df";

function cors(origin:string|null){const allowed=new Set(["https://fadiaboalward.github.io","http://localhost:5173","http://localhost:4173"]);return{"Access-Control-Allow-Origin":origin&&allowed.has(origin)?origin:"https://fadiaboalward.github.io","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-region","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Expose-Headers":"server-timing, x-flh-backend-ms, x-flh-correlation-id, x-flh-db-operations, x-flh-edge-region, x-sb-edge-region","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};}
function fromB64url(s:string){const norm=s.replaceAll("-","+").replaceAll("_","/")+"===".slice((s.length+3)%4),raw=atob(norm);return new Uint8Array([...raw].map(c=>c.charCodeAt(0)));}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
async function hmac(data:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(SERVICE_ROLE),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64url(new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(data))));}
async function learner(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("AUTH_REQUIRED");const[body,sig]=auth.slice(7).trim().split(".");if(!body||!sig||await hmac(body)!==sig)throw new Error("INVALID_SESSION");const p=JSON.parse(new TextDecoder().decode(fromB64url(body)));if(p.typ!=="learner"||p.workspace_id!==WORKSPACE_ID||!p.learner_id)throw new Error("INVALID_SESSION");if(!p.exp||p.exp<Math.floor(Date.now()/1000))throw new Error("SESSION_EXPIRED");return String(p.learner_id);}
function cleanQuiz(q:any){return{id:q.id,slug:q.slug,title:q.title,description:q.description,quiz_kind:q.quiz_kind,unit_id:q.unit_id,book_id:q.book_id,delivery_config:q.delivery_config||{}};}
function buildBook(book:any,units:any[],quizzes:any[]){const unitRows=units.filter(u=>u.book_id===book.id).sort((a,b)=>a.sort_order-b.sort_order).map(u=>({id:u.id,slug:u.slug,title:u.title,sort_order:u.sort_order,metadata:u.metadata||{},quizzes:quizzes.filter(q=>q.unit_id===u.id).map(cleanQuiz)}));const unitIds=new Set(unitRows.map(u=>u.id));const extras=quizzes.filter(q=>q.book_id===book.id&&(!q.unit_id||!unitIds.has(q.unit_id))).map(cleanQuiz);return{id:book.id,code:book.code,title:book.title,grade_level:book.grade_level,school_year:book.school_year,language:book.language,source_kind:book.source_kind,source_metadata:{publisher:book.source_metadata?.publisher??null,official:book.source_metadata?.official===true,support_source:book.source_metadata?.support_source===true},subject:book.subject||null,units:unitRows,extras};}

async function catalog(learnerId:string,trace:any){
  const now=Date.now();
  const[{data:enrs},{data:direct},assignmentResult]=await trace.measure("library.access",{dbOperations:3,execution:"parallel"},()=>Promise.all([admin.from("learner_program_enrollments").select("id,is_primary,started_at,program:learning_programs(id,slug,code,title,description,program_type,grade_level,school_year,primary_language,status)").eq("workspace_id",WORKSPACE_ID).eq("learner_id",learnerId).eq("status","active"),admin.from("learner_content_assignments").select("id,resource_type,resource_id,status").eq("workspace_id",WORKSPACE_ID).eq("learner_id",learnerId).eq("status","active"),admin.from("quiz_assignments").select("id,workspace_id,learner_id,quiz_version_id,status,available_at,due_at,created_at",{count:"exact"}).eq("workspace_id",WORKSPACE_ID).eq("learner_id",learnerId).in("status",["assigned","in_progress","completed"]).limit(JOURNEY_ROW_LIMIT)]));
  const assignmentRows=completeJourneyRows(assignmentResult),eligibleAssignments=eligibleJourneyAssignments(assignmentRows,{workspaceId:WORKSPACE_ID,learnerId,now}),completedAssignments=assignmentRows.filter(a=>a.status==="completed"),assignedVersionIds=[...new Set([...eligibleAssignments,...completedAssignments].map(a=>a.quiz_version_id))];
  let assignedVersions:any[]=[];
  if(assignedVersionIds.length){const result=await trace.measure("library.assigned_versions",{dbOperations:1},()=>admin.from("quiz_versions").select("id,quiz_id",{count:"exact"}).eq("workspace_id",WORKSPACE_ID).eq("state","published").in("id",assignedVersionIds).limit(JOURNEY_ROW_LIMIT));assignedVersions=completeJourneyRows(result);}
  const assignedQuizIds=[...new Set(assignedVersions.map(v=>v.quiz_id))];
  const programs=(enrs||[]).filter((e:any)=>e.program?.status==="active"),programIds=programs.map((e:any)=>e.program.id);let pbooks:any[]=[],pqs:any[]=[];
  if(programIds.length){const[r1,r2]=await trace.measure("library.program_content",{dbOperations:2,execution:"parallel"},()=>Promise.all([admin.from("program_books").select("program_id,book_id,is_required,sort_order").eq("workspace_id",WORKSPACE_ID).in("program_id",programIds).order("sort_order"),admin.from("program_quizzes").select("program_id,quiz_id,sort_order,availability").eq("workspace_id",WORKSPACE_ID).in("program_id",programIds).eq("availability","available").order("sort_order")]));pbooks=r1.data||[];pqs=r2.data||[];}
  const programQuizIds=new Set(pqs.map((pq:any)=>pq.quiz_id)),lookupQuizIds=[...new Set([...assignedQuizIds,...programQuizIds])];
  const directBookIds=(direct||[]).filter((x:any)=>x.resource_type==="book").map((x:any)=>x.resource_id),directUnitIds=(direct||[]).filter((x:any)=>x.resource_type==="unit").map((x:any)=>x.resource_id),directQuizIds=(direct||[]).filter((x:any)=>x.resource_type==="quiz").map((x:any)=>x.resource_id);let directUnits:any[]=[],directQuizzes:any[]=[];
  if(directUnitIds.length){const{data}=await trace.measure("library.direct_units",{dbOperations:1},()=>admin.from("units").select("id,book_id").in("id",directUnitIds));directUnits=data||[];}
  if(directQuizIds.length){const{data}=await trace.measure("library.direct_quizzes",{dbOperations:1},()=>admin.from("quizzes").select("id,book_id,unit_id").eq("workspace_id",WORKSPACE_ID).in("id",directQuizIds));directQuizzes=data||[];}
  const allBookIds=[...new Set([...pbooks.map((x:any)=>x.book_id),...directBookIds,...directUnits.map((x:any)=>x.book_id),...directQuizzes.map((x:any)=>x.book_id).filter(Boolean)])];if(!allBookIds.length&&!lookupQuizIds.length)return{programs:programs.map((e:any)=>({enrollment_id:e.id,is_primary:e.is_primary,...e.program,books:[]})),standalone_books:[],standalone_assessments:[]};
  const quizFields="id,slug,title,description,quiz_kind,delivery_config,book_id,unit_id,status";
  const[{data:books},{data:units},{data:quizzes0},lookupQuizResult]=await trace.measure("library.catalog",{dbOperations:(allBookIds.length?3:0)+(lookupQuizIds.length?1:0),execution:"parallel"},()=>Promise.all([allBookIds.length?admin.from("books").select("id,code,title,grade_level,school_year,language,source_kind,source_metadata,curriculum_id,subject:subjects(id,code,name_ar,name_en)").in("id",allBookIds):Promise.resolve({data:[]}),allBookIds.length?admin.from("units").select("id,book_id,slug,title,sort_order,metadata").in("book_id",allBookIds).order("sort_order"):Promise.resolve({data:[]}),allBookIds.length?admin.from("quizzes").select(quizFields).eq("workspace_id",WORKSPACE_ID).eq("status","active").in("book_id",allBookIds):Promise.resolve({data:[]}),lookupQuizIds.length?admin.from("quizzes").select(quizFields,{count:"exact"}).eq("workspace_id",WORKSPACE_ID).eq("status","active").in("id",lookupQuizIds).limit(JOURNEY_ROW_LIMIT):Promise.resolve({data:[],count:0})]));
  const lookupQuizzes=completeJourneyRows(lookupQuizResult),quizzes=[...new Map([...(quizzes0||[]),...lookupQuizzes].map(q=>[q.id,q])).values()],quizIds=quizzes.map((q:any)=>q.id);let versions:any[]=[];
  if(quizIds.length){const result=await trace.measure("library.published_versions",{dbOperations:1},()=>admin.from("quiz_versions").select("id,workspace_id,quiz_id,version_no,state,support_source:settings->>support_source",{count:"exact"}).eq("workspace_id",WORKSPACE_ID).eq("state","published").in("quiz_id",quizIds).limit(JOURNEY_ROW_LIMIT));versions=completeJourneyRows(result);}
  const published=new Set(versions.map((v:any)=>v.quiz_id)),activeQs=quizzes.filter((q:any)=>published.has(q.id)),bookMap=new Map((books||[]).map((b:any)=>[b.id,b])),unitRows=units||[];
  const programResult=programs.map((e:any)=>{const rows=pbooks.filter((x:any)=>x.program_id===e.program.id).sort((a:any,b:any)=>a.sort_order-b.sort_order),allowed=new Set(pqs.filter((x:any)=>x.program_id===e.program.id).map((x:any)=>x.quiz_id));return{enrollment_id:e.id,is_primary:e.is_primary,started_at:e.started_at,...e.program,books:rows.map((pb:any)=>{const b=bookMap.get(pb.book_id);if(!b)return null;return{...buildBook(b,unitRows,activeQs.filter((q:any)=>allowed.has(q.id))),is_required:pb.is_required,sort_order:pb.sort_order};}).filter(Boolean)};});
  const programBookIds=new Set(pbooks.map((x:any)=>x.book_id)),directBookSet=new Set(directBookIds),directUnitSet=new Set(directUnitIds),directQuizSet=new Set(directQuizIds),standaloneIds=allBookIds.filter(id=>!programBookIds.has(id));const standalone=standaloneIds.map(id=>{const b=bookMap.get(id);if(!b)return null;const allowed=activeQs.filter((q:any)=>q.book_id===id&&(directBookSet.has(id)||(q.unit_id&&directUnitSet.has(q.unit_id))||directQuizSet.has(q.id)));return{...buildBook(b,unitRows,allowed),access_origin:directBookSet.has(id)?"book":"direct"};}).filter(Boolean);
  // Program/eligible version assignments already authorize the start RPC.
  // Include their active published quiz outside books without broadening access.
  const visible:any[]=[];
  for(const book of [...programResult.flatMap((p:any)=>p.books),...standalone]){visible.push(...book.extras);for(const unit of book.units)visible.push(...unit.quizzes);}
  const shownIds=new Set(visible.map(q=>q.id)),candidateIds=new Set([...shownIds,...lookupQuizzes.map(q=>q.id)]),visibleVersions=versions.filter(v=>candidateIds.has(v.quiz_id));
  const{attempts,assignments}=await readJourneyProgress(admin,WORKSPACE_ID,learnerId,visibleVersions.map(v=>v.id),trace,eligibleAssignments);
  const assignedVersionMap=new Map(assignedVersions.map(v=>[v.id,v.quiz_id])),eligibleQuizIds=new Set(eligibleAssignments.map(a=>assignedVersionMap.get(a.quiz_version_id))),completedVersionIds=new Set(completedAssignments.map(a=>a.quiz_version_id));
  const completedQuizIds=new Set(attempts.filter(a=>a.workspace_id===WORKSPACE_ID&&a.learner_id===learnerId&&a.status==="submitted"&&completedVersionIds.has(a.quiz_version_id)).map(a=>assignedVersionMap.get(a.quiz_version_id)));
  const standaloneAssessments=lookupQuizzes.filter(q=>published.has(q.id)&&!shownIds.has(q.id)&&(programQuizIds.has(q.id)||eligibleQuizIds.has(q.id)||completedQuizIds.has(q.id))).map(cleanQuiz);visible.push(...standaloneAssessments);
  for(const q of visible)q.journey=deriveLearnerJourney({quiz:q,versions:visibleVersions,attempts,assignments,workspaceId:WORKSPACE_ID,learnerId,programAccess:programQuizIds.has(q.id),now});
  return{programs:programResult,standalone_books:standalone,standalone_assessments:standaloneAssessments};
}

Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});const trace=createBackendPerformanceTrace({region:Deno.env.get("SB_REGION")||"unknown"});if(req.method!=="POST")return performanceJsonResponse(trace,{error:"METHOD_NOT_ALLOWED"},405,cors(origin));try{const body=await req.json().catch(()=>({})),action=String(body.action||"catalog");if(action!=="catalog")return performanceJsonResponse(trace,{error:"UNKNOWN_ACTION"},400,cors(origin));trace.setAction(action);const learnerId=await trace.measure("authentication",{},()=>learner(req));return performanceJsonResponse(trace,await catalog(learnerId,trace),200,cors(origin));}catch(e){const msg=e instanceof Error?e.message:"SERVER_ERROR",status=["AUTH_REQUIRED","INVALID_SESSION","SESSION_EXPIRED"].includes(msg)?401:500;return performanceJsonResponse(trace,{error:msg},status,cors(origin));}});
