create index if not exists adaptive_events_attempt_workspace_fk_idx on public.adaptive_events(quiz_attempt_id, workspace_id);
create index if not exists adaptive_events_learner_workspace_fk_idx on public.adaptive_events(learner_id, workspace_id);
create index if not exists adaptive_events_concept_workspace_fk_idx on public.adaptive_events(concept_id, workspace_id);
create index if not exists learner_concept_mastery_learner_workspace_fk_idx on public.learner_concept_mastery(learner_id, workspace_id);
create index if not exists learner_concept_mastery_concept_workspace_fk_idx on public.learner_concept_mastery(concept_id, workspace_id);
create index if not exists learning_concepts_subject_fk_idx on public.learning_concepts(subject_id);
create index if not exists learning_concepts_curriculum_fk_idx on public.learning_concepts(curriculum_id);
create index if not exists question_families_concept_workspace_fk_idx on public.question_families(concept_id, workspace_id);
create index if not exists question_families_subject_fk_idx on public.question_families(subject_id);
create index if not exists question_families_curriculum_fk_idx on public.question_families(curriculum_id);
create index if not exists quiz_answer_attempts_quiz_attempt_workspace_fk_idx on public.quiz_answer_attempts(quiz_attempt_id, workspace_id);
create index if not exists quiz_answer_attempts_question_workspace_fk_idx on public.quiz_answer_attempts(question_id, workspace_id);
create index if not exists quiz_attempt_question_queue_attempt_workspace_fk_idx on public.quiz_attempt_question_queue(quiz_attempt_id, workspace_id);
create index if not exists quiz_attempt_question_queue_question_workspace_fk_idx on public.quiz_attempt_question_queue(question_id, workspace_id);
create index if not exists quiz_attempt_question_queue_parent_workspace_fk_idx on public.quiz_attempt_question_queue(parent_question_id, workspace_id);
create index if not exists quiz_attempt_question_queue_concept_workspace_fk_idx on public.quiz_attempt_question_queue(concept_id, workspace_id);
create index if not exists quiz_question_concepts_question_workspace_fk_idx on public.quiz_question_concepts(question_id, workspace_id);
create index if not exists quiz_question_concepts_concept_workspace_fk_idx on public.quiz_question_concepts(concept_id, workspace_id);
create index if not exists quiz_question_hints_question_workspace_fk_idx on public.quiz_question_hints(question_id, workspace_id);
create index if not exists quiz_questions_family_workspace_fk_idx on public.quiz_questions(question_family_id, workspace_id);
